version: '3'

services:
  discodns:
    build: ./docker
    ports:
      - "60053:53/tcp"
      - "60053:53/udp"
    depends_on:
      - etcd0
      - etcd1
    environment:
      ETCD_HOST: etcd0
      ETCD_PORT: 2379

  etcd0:
    image: quay.io/coreos/etcd:v3.1.2
    restart: always
    environment:
      ETCD_NAME: etcd0
      ETCD_DATA_DIR: /data
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd0:2379,http://etcd0:4001
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379,http://0.0.0.0:4001
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd0:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster-1
      ETCD_INITIAL_CLUSTER: etcd0=http://etcd0:2380,etcd1=http://etcd1:2380
      ETCD_INITIAL_CLUSTER_STATE: new

  etcd1:
    image: quay.io/coreos/etcd:v3.1.2
    restart: always
    ports:
      - "62379:2379"
    volumes:
      - /tmp/discodns-etcd1:/data
    environment:
      ETCD_NAME: etcd1
      ETCD_DATA_DIR: /data
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379,http://etcd1:4001
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379,http://0.0.0.0:4001
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster-1
      ETCD_INITIAL_CLUSTER: etcd0=http://etcd0:2380,etcd1=http://etcd1:2380
      ETCD_INITIAL_CLUSTER_STATE: new
